Skin scandir tests on generic Linux when using our GHA.

diff --git a/chevah_build b/chevah_build
--- a/chevah_build
+++ b/chevah_build
@@ -30,7 +30,7 @@ SUBPROCESS32_VERSION="3.5.4"
 # Versions no longer upgradable because of Python 2 deprecation.
 PIP_VERSION="20.3.4"
 # For pip <21.1.
-SAFETY_FALSE_POSITIVES_OPTS="-i 40291"
+SAFETY_IGNORED_OPTS="-i 40291"
 # setuptools 44.x is the last series to support Python 2.7.
 # More at https://github.com/pypa/setuptools/pull/1955.
 SETUPTOOLS_VERSION="44.1.1"
@@ -702,6 +702,13 @@ command_test() {
             ;;
         aix*)
             (>&2 echo -e "\tSkipping because of upstream issues.")
+            ;;
+        lnx)
+            if [ x"$CHEVAH_CONTAINER" = x"yes" ]; then
+                (>&2 echo -e "\tSkipping as it fails under Docker on CentOS 5.")
+            else
+                execute $PYTHON_BIN ${SCANDIR_FOLDER}/test/run_tests.py
+            fi
             ;;
         *)
             # UTF-8 locale is needed for the tests to pass on remaining OS'es.
