Only talk about installing packages if needed.

diff --git a/chevah_build b/chevah_build
--- a/chevah_build
+++ b/chevah_build
@@ -156,7 +156,7 @@ install_dependencies() {
             check_command='rpm --query'
         ;;
         linux|aix*|solaris*|osx*)
-            packages=""
+            packages=''
             install_command=''
             check_command=''
         ;;
@@ -165,15 +165,16 @@ install_dependencies() {
     # We install one package after another since some package managers
     # (I am looking at you yum) will exit with 0 exit code if at least
     # one package was successfully installed.
-    echo "Installing required packages..."
-    for package in $packages ; do
-    $check_command $package
-    if [ $? -ne 0 ]; then
-            execute $install_command $package \
-                && INSTALLED_PACKAGES="$INSTALLED_PACKAGES $package"
-        fi
-    done
-
+    if [ -n "$packages" ]; then
+        echo "Installing required packages using sudo..."
+        for package in $packages ; do
+            $check_command $package
+            if [ $? -ne 0 ]; then
+                execute $install_command $package \
+                    && INSTALLED_PACKAGES="$INSTALLED_PACKAGES $package"
+            fi
+        done
+    fi
 }
 
 
