Skip scandir tests on arm64 too.

diff --git a/chevah_build b/chevah_build
--- a/chevah_build
+++ b/chevah_build
@@ -713,7 +713,10 @@ command_test() {
         aix*)
             (>&2 echo -e "\tSkipping because of upstream issues.")
             ;;
-        lnx*)
+        lnx-arm64)
+            (>&2 echo -e "\tSkipping as it now fails on ARM64.")
+            ;;
+        lnx-x64)
             if [ x"$CHEVAH_CONTAINER" = x"yes" ]; then
                 (>&2 echo -e "\tSkipping as it fails under Docker on CentOS 5.")
             else
