Fix CVE-2022-0391 for Python's urlparse. (#169)
* Fixed CVE-2022-0391 for Python's urlparse.

* Bash checks for the chevahbs scripts.

* Removed some unused variables from chevahbs scripts.

* Try generic musl build.

* Fixed musl version check for 1.2 and newer.

* Updated OpenSSL sources to 1.1.1q

* Updated OpenSSL 1.1.1 version in our scripts and docs.

* Actually updated the docs for OpenSSL 1.1.1q.

* Updated own tests for generic musl Linux build.

* Backported OpenSSL build fix for macOS.

* Ignore dparse issue for now.

* Updated cffi and psutil to the latest versions.

* Updated cffi sources to 1.15.1.

* Try a different psutil check.

* Pin psutil to version 5.9.0 on generic Linux builds.

* Build generic musl version on Alpine 3.12.

* Use a saved paxctl on Alpine 3.12.

* Save paxctl on Alpine 3.12 in an already existing path dir.

* Changes after own review.

* Updated and reorganized external deps sheets.

* Updated list of RHEL clones from server repo.

* Temporarily disabled ARM64 builds.

* More Alpine-related cleanups and fixes.

* One more Alpine-related fix.

diff --git a/chevah_build b/chevah_build
--- a/chevah_build
+++ b/chevah_build
@@ -6,9 +6,11 @@
 # test
 # compat (for the compat repo tests)
 
-set -o nounset
-set -o errexit
-set -o pipefail
+# Bash checks
+set -o nounset    # always check if variables exist
+set -o errexit    # always exit on error
+set -o errtrace   # trap errors in functions as well
+set -o pipefail   # don't ignore exit codes when piping output
 
 PYTHON_BUILD_VERSION="2.7.18"
 LIBFFI_VERSION="3.4.2"
@@ -17,14 +19,14 @@ BZIP2_VERSION="1.0.8"
 # We statically build the BSD libedit on selected platforms to get the
 # readline module available without linking to the GPL-only readline libs.
 LIBEDIT_VERSION="20170329-3.1"
-OPENSSL_VERSION="1.1.1n"
+OPENSSL_VERSION="1.1.1q"
 SQLITE_VERSION="3.37.2"
 
 # Python modules versions to be used everywhere possible.
 PYSQLITE_VERSION="2.8.3"
-CFFI_VERSION="1.15.0"
+CFFI_VERSION="1.15.1"
 SCANDIR_VERSION="1.10.0"
-PSUTIL_VERSION="5.9.0"
+PSUTIL_VERSION="5.9.2"
 SUBPROCESS32_VERSION="3.5.4"
 
 # Versions no longer upgradable because of Python 2 deprecation.
@@ -33,8 +35,8 @@ PYOPENSSL_VERSION="21.0.0"
 # Backported fix for https://github.com/pypa/pip/issues/9827
 # at https://github.com/chevah/pip/tree/20.3.4chevah.
 PIP_VERSION="20.3.4chevah1"
-# For pip <21.1 and click <8.0.0.
-SAFETY_IGNORED_OPTS="-i 40291 -i 47833"
+# For pip <21.1, click <8.0.0, dparse <0.5.2.
+SAFETY_IGNORED_OPTS="-i 40291 -i 47833 -i 50571"
 # setuptools 44.x is the last series to support Python 2.7.
 # More at https://github.com/pypa/setuptools/pull/1955.
 SETUPTOOLS_VERSION="44.1.1"
@@ -124,7 +126,6 @@ BUILD_FOLDER='build'
 COMMON_PKGS="gcc make m4 automake libtool patch"
 DEB_PKGS="$COMMON_PKGS git libffi-dev zlib1g-dev libncurses5-dev libssl-dev"
 RPM_PKGS="$COMMON_PKGS git libffi-devel zlib-devel ncurses-devel openssl-devel"
-APK_PKGS="$COMMON_PKGS git zlib-dev musl-dev openssl-dev linux-headers lddtree"
 # No automated Windows package management, but here's what it's needed.
 CHOCO_PKGS="vcpython27 make git StrawberryPerl nasm 7zip"
 
@@ -279,7 +280,7 @@ case $OS in
         # libffi not available in the base system, only as port/package.
         export BUILD_LIBFFI="yes"
         ;;
-    lnx)
+    lnx*)
         export CC="gcc"
         export CXX="g++"
         export MAKE="make"
@@ -294,18 +295,19 @@ case $OS in
         export PATH="/usr/local/bin:$PATH"
         # In particular, Perl's Test::Simple and its deps are required.
         execute perl -MTest::Simple -e 1
-        ;;
-    alpine*)
-        # Do not depend on libffi and ncurses-libs Alpine packages.
-        # It's better to run on minimal Alpine containers.
-        export BUILD_LIBFFI="yes"
-        export BUILD_LIBEDIT="no"
-        export CC="gcc"
-        export CXX="g++"
-        export MAKE="make"
+        # Version 5.9.2 of psutil not working properly on CentOS 5.
+        PIP_LIBRARIES="\
+            cryptography==${CRYPTOGRAPHY_VERSION} \
+            pyOpenSSL==${PYOPENSSL_VERSION} \
+            scandir==${SCANDIR_VERSION} \
+            subprocess32==${SUBPROCESS32_VERSION} \
+            bcrypt==${BCRYPT_VERSION} \
+            psutil=="5.9.0" \
+            setproctitle==${SETPROCTITLE_VERSION}
+            "
         ;;
     *)
-        # Only supported Linux distributions other than Alpine should be left.
+        # Only supported Linux distributions should be left.
         export CC="gcc"
         export CXX="g++"
         export MAKE="make"
@@ -367,13 +369,8 @@ check_dependencies() {
             packages=$RPM_PKGS
             check_command="rpm --query"
             ;;
-        alpine*)
-            # Alpine 3.9 switched back to OpenSSL as default.
-            packages=$APK_PKGS
-            check_command="apk info -q -e"
-            ;;
         # On remaining OS'es we just check for some of the needed commands.
-        lnx)
+        lnx*)
             # Generic Linux builds need Perl 5.10.0+ for building OpenSSL.
             # For testing OpenSSL, Test::More 0.96 or newer is needed.
             packages="$CC make m4 git patch perl"
@@ -485,8 +482,7 @@ command_build() {
                 ${INSTALL_FOLDER}/lib/pkgconfig/:${PKG_CONFIG_PATH}"
         elif [ "${OS%lnx*}" = "" -o "${OS%macos*}" = "" ]; then
             # Passing -rpath to ldd is needed for building cryptography w/ pip.
-            export LDFLAGS="-L${INSTALL_FOLDER}/lib64/ \
-                -Wl,-rpath,${INSTALL_FOLDER}/lib64/ ${LDFLAGS}"
+            export LDFLAGS="-Wl,-rpath,${INSTALL_FOLDER}/lib/ ${LDFLAGS}"
             export PKG_CONFIG_PATH="\
                 ${INSTALL_FOLDER}/lib64/pkgconfig/:${PKG_CONFIG_PATH}"
         fi
