Fixed CVE-2022-0391 for Python's urlparse.

diff --git a/chevah_build b/chevah_build
--- a/chevah_build
+++ b/chevah_build
@@ -6,9 +6,11 @@
 # test
 # compat (for the compat repo tests)
 
-set -o nounset
-set -o errexit
-set -o pipefail
+# Bash checks
+set -o nounset    # always check if variables exist
+set -o errexit    # always exit on error
+set -o errtrace   # trap errors in functions as well
+set -o pipefail   # don't ignore exit codes when piping output
 
 PYTHON_BUILD_VERSION="2.7.18"
 LIBFFI_VERSION="3.4.2"
@@ -485,8 +487,7 @@ command_build() {
                 ${INSTALL_FOLDER}/lib/pkgconfig/:${PKG_CONFIG_PATH}"
         elif [ "${OS%lnx*}" = "" -o "${OS%macos*}" = "" ]; then
             # Passing -rpath to ldd is needed for building cryptography w/ pip.
-            export LDFLAGS="-L${INSTALL_FOLDER}/lib64/ \
-                -Wl,-rpath,${INSTALL_FOLDER}/lib64/ ${LDFLAGS}"
+            export LDFLAGS="-Wl,-rpath,${INSTALL_FOLDER}/lib/ ${LDFLAGS}"
             export PKG_CONFIG_PATH="\
                 ${INSTALL_FOLDER}/lib64/pkgconfig/:${PKG_CONFIG_PATH}"
         fi
