Refactored _install() for libffi's chevahbs.

diff --git a/src/libffi/chevahbs b/src/libffi/chevahbs
--- a/src/libffi/chevahbs
+++ b/src/libffi/chevahbs
@@ -22,40 +22,38 @@ chevahbs_compile() {
 chevahbs_install() {
     install_folder=$1
 
-    if [ x${ARCH##ppc} != x"$ARCH" ]; then
-        # libffi installs its headers in $PREFIX/lib/libffi-$VERSION/include,
-        # instead of $PREFIX/include, so we copy them manually to a temporary
-        # location.
-        # From there we will copy them just in time for building Python sources.
-        # For Python's setup.py to pick them up, we will augment CPPFLAGS with
-        # the include's location and LDFLAGS with the location of the libs.
-        local temp_folder=$INSTALL_FOLDER/tmp/libffi
-        execute mkdir -p $temp_folder
-
-        execute cp powerpc-ibm-aix*/.libs/* $temp_folder
-        execute cp powerpc-ibm-aix*/include/*.h $temp_folder
-    elif [ "$OS" = "solaris10" ]; then
-        # I don't know why it is skip... but doing the actual install will
-        # break the build.
-        echo 'Skipping installation of libffi on Solaris 10.'
-    elif [ "$OS" = "solaris11" ]; then
-        # I don't know why it is skip... but doing the actual install will
-        # break the build.
-        echo 'Skipping installation of libffi on Solaris 11.'
-    else
-        execute $MAKE install DESTDIR=$INSTALL_FOLDER
-
-        # libffi installs its headers in $PREFIX/lib/libffi-$VERSION/include,
-        # instead of $PREFIX/include, so we copy them manually to the default
-        # location.
-        execute mkdir -p $INSTALL_FOLDER/include
-        execute cp $INSTALL_FOLDER/lib/libffi-*/include/* $INSTALL_FOLDER/include
-        # On some systems libffi in installed in /lib64 and then cffi is
-        # searching for it in /lib.
-        # THis affect RHEL, SLES and OpenBSD.
-        cp $INSTALL_FOLDER/lib64/* $INSTALL_FOLDER/lib
-        echo 'cffi done... here to ignore a possible previous error'
-    fi
+    case "$OS" in
+        aix*)
+            # libffi puts its headers in $PREFIX/lib/libffi-$VERSION/include,
+            # instead of $PREFIX/include, so we copy them manually to a
+            # temporary location.
+            # From there we will copy them in time for building Python sources.
+            # For Python's setup.py to pick them up, we'll augment CPPFLAGS with
+            # the include's location and LDFLAGS with the location of the libs.
+            local temp_folder=$INSTALL_FOLDER/tmp/libffi
+            execute mkdir -p $temp_folder
+            execute cp powerpc-ibm-aix*/.libs/* $temp_folder
+            execute cp powerpc-ibm-aix*/include/*.h $temp_folder
+            ;;
+        solaris*)
+            # For some reason the actual install breaks the build on some OS'es.
+            (>&2 echo -e "\tSkipping installation of libffi on ${OS}...")
+            ;;
+        *)
+            execute $MAKE install DESTDIR=$INSTALL_FOLDER
+            # libffi installs its headers in $PREFIX/lib/libffi-$VERSION/include
+            # instead of $PREFIX/include, so we copy them manually to the
+            # default location.
+            execute mkdir -p $INSTALL_FOLDER/include
+            execute cp $INSTALL_FOLDER/lib/libffi-*/include/* \
+                       $INSTALL_FOLDER/include/
+            # On some systems libffi is installed in /lib64 and then cffi is
+            # searching for it in /lib.
+            # This affects RHEL, SLES and OpenBSD.
+            cp $INSTALL_FOLDER/lib64/* $INSTALL_FOLDER/lib/
+            echo 'cffi done... here to ignore a possible previous error'
+            ;;
+    esac
 }
 
 
