Try adapting the pyca/infra BATs for our build.

diff --git a/src/openssl/chevahbs b/src/openssl/chevahbs
--- a/src/openssl/chevahbs
+++ b/src/openssl/chevahbs
@@ -7,44 +7,66 @@
 
 
 chevahbs_configure() {
-    # We want static builds only, so that we don't have to mess with LIBPATH.
-    CONF_OPTS="no-shared"
-    # OpenSSL's build requires an absolute path for --prefix,
-    # so we don't use --prefix="" as in the other chevahbs scripts.
-    execute ./config --prefix="$INSTALL_FOLDER" $CONF_OPTS
+    case $OS in
+        win*)
+            echo "Nothing to configure on Windows."
+            ;;
+        *)
+            # Static builds only, so that we don't have to mess with LIBPATH.
+            CONF_OPTS="no-shared"
+            # OpenSSL's build requires an absolute path for --prefix,
+            # so we don't use --prefix="" as in the other chevahbs scripts.
+            execute ./config --prefix="$INSTALL_FOLDER" $CONF_OPTS
+            ;;
+    esac
 }
 
 
 chevahbs_compile() {
     # On AIX, OpenSSL's tests have an ~1/6 chance of passing.
     # Just repeating the tests is not enough, a whole rebuild is needed.
-    if [ "${OS%aix*}" = "" ]; then
-        for i in $(seq 1 20); do
-            echo "OpenSSL build ROUND ${i}..."
-            execute $MAKE
-            $MAKE test
-            tests_error_code=$?
-            if [ $tests_error_code -eq 0 ]; then
-                echo "OpenSSL tests were SUCCESSFUL in ROUND ${i}."
-                break
-            else
-                execute $MAKE clean
+    case $OS in
+        win*)
+            # The included Perl is not good enough.
+            export PATH=/c/Strawberry/perl/bin/:$PATH
+            # Build with VisualStudio 2010 using BATs from pyca/infra.
+            ../../src/openssl/win_${ARCH}_2010.bat
+            ;;
+        aix*)
+            for i in $(seq 1 20); do
+                echo "OpenSSL build ROUND ${i}..."
+                execute $MAKE
+                $MAKE test
+                tests_error_code=$?
+                if [ $tests_error_code -eq 0 ]; then
+                    echo "OpenSSL tests were SUCCESSFUL in ROUND ${i}."
+                    break
+                else
+                    execute $MAKE clean
+                fi
+            done
+            if [ $tests_error_code -ne 0 ]; then
+                echo "OpenSSL tests failed $i times in a row."
+                exit 69
             fi
-        done
-        if [ $tests_error_code -ne 0 ]; then
-            echo "OpenSSL tests failed $i times in a row."
-            exit 69
-        fi
-    else
-        execute $MAKE
-        execute $MAKE test
-    fi
+            ;;
+        *)
+            execute $MAKE
+            execute $MAKE test
+            ;;
+    esac
 }
 
 
 chevahbs_install() {
-    install_folder=$1
-    execute $MAKE install
+    case $OS in
+        win*)
+            echo "Libs/headers installed through the build BAT file."
+            ;;
+        *)
+            install_folder=$1
+            execute $MAKE install
+            ;;
 }
 
 
