Back to cloning sources independently on Linux.

diff --git a/.github/workflows/bare.yaml b/.github/workflows/bare.yaml
--- a/.github/workflows/bare.yaml
+++ b/.github/workflows/bare.yaml
@@ -38,29 +38,44 @@ jobs:
       if: startsWith(matrix.runs-on, 'ubuntu')
       run: sudo apt-get install -y libncurses5-dev
 
-    - name: Clone sources
-      uses: actions/checkout@v2
-      # Required to get the correct git rev to use in Python's version.
-      with:
-        ref: ${{ github.event.after }}
+    # Git's version on our ARM64 runner is too old for actions/checkout to
+    # create a local repo. Beware this fails on opening a new PR.
+    - name: Clone sources independently
+      run: |
+        git init $CHEVAH_REPO
+        cd $CHEVAH_REPO
+        # Cleanup the repo.
+        git rev-parse --symbolic-full-name --verify --quiet HEAD || true
+        git rev-parse --symbolic-full-name --branches || true
+        git remote remove origin || true
+        # Update repo token.
+        git remote add origin https://github.com/chevah/$CHEVAH_REPO
+        git fetch --no-tags --prune origin
+        # Prepare the code.
+        git clean -f
+        git reset --hard ${{ github.event.after }}
 
     - name: Detect OS and build Python
       run: |
+        cd python-package/
         ./brink.sh detect_os
         ./chevah_build build
 
     - name: Own tests
       run: |
+        cd python-package/
         ./chevah_build test
 
     - name: Compat tests
       run: |
+        cd python-package/
         ./chevah_build compat
 
     # Upload using a (per-OS selected) sftp command, then show final links.
     - name: Upload testing package
       run: |
         mkdir -pv ~/.ssh/
+        cd python-package/
         touch priv_key
         chmod 600 priv_key
         echo "${{ secrets.SFTPPLUS_BIN_PRIV_KEY }}" > priv_key
